services:
  - type: web
    name: crowd-monitor-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.10.5
